name: Continuous Integration/Continuous Deployment
on: [push]
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      REGION: ${{ secrets.REGION }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set environment
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          export GOOGLE_APPLICATION_CREDENTIALS=$(python api_db/helpers/setter.py)
      - name: Set up GCLOUD SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Build and Push
        run: |
          docker build . -t $REGISTRY_NAME:$GITHUB_SHA
          gcloud auth configure-docker -q
          sudo -u $USER docker push $REGISTRY_NAME:$GITHUB_SHA
      - name: view files
        run: |
          pwd
      - name: Deploy to Cloud Run
        run: |
          gcloud run services update $SERVICE_NAME --region=$REGION --image=$REGISTRY_NAME:$GITHUB_SHA
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: '345.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Create zip file
        run: |
          zip -r consume_api.zip ./consume_api
      - name: Copy folder to GCS
        run: |
          gsutil cp consume_api.zip  gs://github-code-globant/